// <auto-generated />

using Matech.Common.Scaffolding.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Matech.Common.Scaffolding.Repository.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Matech.Common.Scaffolding.Core.Entities.TestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AnotherProperty")
                        .HasColumnType("text");

                    b.Property<string>("TestProperty")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnotherProperty = "AnotherPropertyOne",
                            TestProperty = "TestPropertyOne"
                        },
                        new
                        {
                            Id = 2,
                            AnotherProperty = "AnotherPropertyTwo",
                            TestProperty = "TestPropertyTwo"
                        },
                        new
                        {
                            Id = 3,
                            AnotherProperty = "AnotherPropertyThree",
                            TestProperty = "TestPropertyThree"
                        },
                        new
                        {
                            Id = 4,
                            AnotherProperty = "AnotherPropertyFour"
                        },
                        new
                        {
                            Id = 5,
                            AnotherProperty = "AnotherProperty",
                            TestProperty = " "
                        },
                        new
                        {
                            Id = 6,
                            TestProperty = ""
                        },
                        new
                        {
                            Id = 7,
                            AnotherProperty = "7",
                            TestProperty = "TestPropertyOne"
                        },
                        new
                        {
                            Id = 8,
                            AnotherProperty = "AnotherPropertyOne",
                            TestProperty = "TestPropertYEight"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
